package com.github.javachaos.javaneuralnetwork.examples;

import java.util.ArrayList;
import java.util.List;

/**
 * Teacher-student benchmark generated by a tiny but structurally complete transformer block.
 */
public final class RealTransformerBlockProblem extends NeuroEvolutionProblem {

    private static final String KEY = "real-transformer-block";
    private static final int SEQUENCE_LENGTH = 4;
    private static final int VOCAB_SIZE = 8;
    private static final int MODEL_DIMENSIONS = 4;
    private static final int HEADS = 2;
    private static final int HEAD_DIMENSIONS = 2;
    private static final int MLP_DIMENSIONS = 8;
    private static final int RESIDUAL_OUTPUTS = SEQUENCE_LENGTH * MODEL_DIMENSIONS;
    private static final int NORM_OUTPUTS = SEQUENCE_LENGTH * MODEL_DIMENSIONS;
    private static final int QKV_OUTPUTS_PER_KIND = HEADS * SEQUENCE_LENGTH * HEAD_DIMENSIONS;
    private static final int ATTENTION_OUTPUTS_PER_HEAD = SEQUENCE_LENGTH * SEQUENCE_LENGTH;
    private static final int MLP_OUTPUTS = SEQUENCE_LENGTH * MLP_DIMENSIONS;
    private static final int FINAL_OFFSET = 0;
    private static final int NORM1_OFFSET = FINAL_OFFSET + RESIDUAL_OUTPUTS;
    private static final int NORM2_OFFSET = NORM1_OFFSET + NORM_OUTPUTS;
    private static final int QUERY_OFFSET = NORM2_OFFSET + NORM_OUTPUTS;
    private static final int KEY_OFFSET = QUERY_OFFSET + QKV_OUTPUTS_PER_KIND;
    private static final int VALUE_OFFSET = KEY_OFFSET + QKV_OUTPUTS_PER_KIND;
    private static final int ATTENTION_OFFSET = VALUE_OFFSET + QKV_OUTPUTS_PER_KIND;
    private static final int MLP_OFFSET = ATTENTION_OFFSET + HEADS * ATTENTION_OUTPUTS_PER_HEAD;
    private static final int OUTPUT_DIMENSIONS = MLP_OFFSET + MLP_OUTPUTS;
    private static final double ATTENTION_OBJECTIVE_WEIGHT = 2.5;
    private static final double MLP_OBJECTIVE_WEIGHT = 1.25;
    private static final double NORM_OBJECTIVE_WEIGHT = 0.85;
    private static final double LAYER_NORM_EPSILON = 1.0e-5;
    private static final double ATTENTION_LOGIT_SCALE = 1.45;
    private static final NeuroEvolutionFreeEnergyProfile FREE_ENERGY_PROFILE =
            NeuroEvolutionFreeEnergyProfile.predictiveCoding(0.025, 1.0, 0.30, 0.006, 4.0);

    private static final int BOS = 0;
    private static final String DESCRIPTION = "Real transformer block is a teacher-student benchmark generated by a "
            + "fixed miniature pre-norm transformer layer. The four raw inputs are scrambled token codes. The target "
            + "exposes the final residual stream plus the block internals a real implementation depends on: layer "
            + "normalization outputs, two-head Q/K/V projections, scaled dot-product attention maps, and GELU MLP "
            + "hidden activations. This pressures evolved learners to approximate the block's actual algorithmic "
            + "contract rather than only matching a small final output surface.";
    private static final String[] TOKEN_LABELS = {
            "BOS", "THE", "A", "RED", "BLUE", "CUBE", "SPHERE", "GLOWS"
    };
    private static final double[] TOKEN_CODES = {
            0.00, 0.82, 0.17, 0.61, 0.34, 0.95, 0.08, 0.73
    };

    private static final double[][] TOKEN_EMBEDDINGS = matrix(VOCAB_SIZE, MODEL_DIMENSIONS, 0.37, 1.00);
    private static final double[][] POSITION_EMBEDDINGS = matrix(SEQUENCE_LENGTH, MODEL_DIMENSIONS, 1.13, 0.42);
    private static final double[] NORM1_GAMMA = vector(MODEL_DIMENSIONS, 0.19, 1.00, 0.12);
    private static final double[] NORM1_BETA = vector(MODEL_DIMENSIONS, 0.43, 0.00, 0.08);
    private static final double[] NORM2_GAMMA = vector(MODEL_DIMENSIONS, 0.67, 1.00, 0.11);
    private static final double[] NORM2_BETA = vector(MODEL_DIMENSIONS, 0.91, 0.00, 0.07);
    private static final double[][][] QUERY_PROJECTIONS =
            tensor(HEADS, HEAD_DIMENSIONS, MODEL_DIMENSIONS, 1.29, 1.05);
    private static final double[][][] KEY_PROJECTIONS =
            tensor(HEADS, HEAD_DIMENSIONS, MODEL_DIMENSIONS, 1.71, 1.00);
    private static final double[][][] VALUE_PROJECTIONS =
            tensor(HEADS, HEAD_DIMENSIONS, MODEL_DIMENSIONS, 2.03, 0.96);
    private static final double[][] QUERY_BIASES = headBiases(2.41, 0.10);
    private static final double[][] KEY_BIASES = headBiases(2.83, 0.09);
    private static final double[][] VALUE_BIASES = headBiases(3.17, 0.11);
    private static final double[][] ATTENTION_OUTPUT_PROJECTION =
            matrix(MODEL_DIMENSIONS, HEADS * HEAD_DIMENSIONS, 3.59, 0.92);
    private static final double[] ATTENTION_OUTPUT_BIAS = vector(MODEL_DIMENSIONS, 3.97, 0.00, 0.07);
    private static final double[][] MLP_INPUT_PROJECTION = matrix(MLP_DIMENSIONS, MODEL_DIMENSIONS, 4.31, 1.18);
    private static final double[] MLP_INPUT_BIAS = vector(MLP_DIMENSIONS, 4.73, 0.00, 0.11);
    private static final double[][] MLP_OUTPUT_PROJECTION = matrix(MODEL_DIMENSIONS, MLP_DIMENSIONS, 5.11, 0.82);
    private static final double[] MLP_OUTPUT_BIAS = vector(MODEL_DIMENSIONS, 5.47, 0.00, 0.06);

    public RealTransformerBlockProblem(final int gridSize) {
        super(
                KEY,
                "Real transformer block",
                DESCRIPTION,
                List.of(
                        "real-transformer",
                        "layer-norm-transformer",
                        "gelu-transformer",
                        "modern-transformer-block",
                        "transformer-real-block"),
                SEQUENCE_LENGTH,
                OUTPUT_DIMENSIONS,
                buildTrainingSamples(),
                buildGeneralizationSamples(Math.max(gridSize, DEFAULT_GRID_SIZE)),
                buildJitterSamples(),
                buildKernelCenters(),
                false,
                RealTransformerBlockProblem::targetValue);
    }

    public double[] encodeTokenSequence(final int... tokens) {
        return sequence(tokens);
    }

    @Override
    public String outputLabel(final int outputIndex) {
        if (outputIndex < 0 || outputIndex >= OUTPUT_DIMENSIONS) {
            throw new IllegalArgumentException("Output index must be in the real transformer block output range.");
        }
        if (outputIndex < NORM1_OFFSET) {
            return residualLabel("Y", outputIndex - FINAL_OFFSET);
        }
        if (outputIndex < NORM2_OFFSET) {
            return residualLabel("LN1", outputIndex - NORM1_OFFSET);
        }
        if (outputIndex < QUERY_OFFSET) {
            return residualLabel("LN2", outputIndex - NORM2_OFFSET);
        }
        if (outputIndex < ATTENTION_OFFSET) {
            return qkvOutputLabel(outputIndex);
        }
        if (outputIndex < MLP_OFFSET) {
            int index = outputIndex - ATTENTION_OFFSET;
            int head = index / ATTENTION_OUTPUTS_PER_HEAD;
            int headIndex = index % ATTENTION_OUTPUTS_PER_HEAD;
            return "A" + head + ".Q" + (headIndex / SEQUENCE_LENGTH) + ".K" + (headIndex % SEQUENCE_LENGTH);
        }
        int mlpIndex = outputIndex - MLP_OFFSET;
        return "MLP.P" + (mlpIndex / MLP_DIMENSIONS) + ".H" + (mlpIndex % MLP_DIMENSIONS);
    }

    @Override
    public List<NeuroEvolutionOutputGroup> outputGroups() {
        return List.of(
                new NeuroEvolutionOutputGroup("Final residual stream", FINAL_OFFSET, NORM1_OFFSET),
                new NeuroEvolutionOutputGroup("Layer norm 1 outputs", NORM1_OFFSET, NORM2_OFFSET, NORM_OBJECTIVE_WEIGHT),
                new NeuroEvolutionOutputGroup("Layer norm 2 outputs", NORM2_OFFSET, QUERY_OFFSET, NORM_OBJECTIVE_WEIGHT),
                new NeuroEvolutionOutputGroup("Query projections", QUERY_OFFSET, KEY_OFFSET),
                new NeuroEvolutionOutputGroup("Key projections", KEY_OFFSET, VALUE_OFFSET),
                new NeuroEvolutionOutputGroup("Value projections", VALUE_OFFSET, ATTENTION_OFFSET),
                new NeuroEvolutionOutputGroup(
                        "Attention head 0",
                        ATTENTION_OFFSET,
                        ATTENTION_OFFSET + ATTENTION_OUTPUTS_PER_HEAD,
                        ATTENTION_OBJECTIVE_WEIGHT),
                new NeuroEvolutionOutputGroup(
                        "Attention head 1",
                        ATTENTION_OFFSET + ATTENTION_OUTPUTS_PER_HEAD,
                        MLP_OFFSET,
                        ATTENTION_OBJECTIVE_WEIGHT),
                new NeuroEvolutionOutputGroup("MLP GELU hidden", MLP_OFFSET, OUTPUT_DIMENSIONS, MLP_OBJECTIVE_WEIGHT));
    }

    @Override
    public NeuroEvolutionFreeEnergyProfile freeEnergyProfile() {
        return FREE_ENERGY_PROFILE;
    }

    public String tokenLabel(final int token) {
        if (token < BOS || token >= VOCAB_SIZE) {
            throw new IllegalArgumentException("Token must be in the real transformer block vocabulary range.");
        }
        return TOKEN_LABELS[token];
    }

    private static List<NeuroEvolutionSample> buildTrainingSamples() {
        List<NeuroEvolutionSample> samples = new ArrayList<>();
        for (int first = BOS; first < VOCAB_SIZE; first++) {
            for (int second = BOS; second < VOCAB_SIZE; second++) {
                for (int third = BOS; third < VOCAB_SIZE; third++) {
                    for (int fourth = BOS; fourth < VOCAB_SIZE; fourth++) {
                        if (sampleBucket(first, second, third, fourth) < 4) {
                            samples.add(sample(first, second, third, fourth));
                        }
                    }
                }
            }
        }
        return List.copyOf(samples);
    }

    private static List<NeuroEvolutionSample> buildGeneralizationSamples(final int gridSize) {
        List<NeuroEvolutionSample> samples = new ArrayList<>();
        for (int first = BOS; first < VOCAB_SIZE; first++) {
            for (int second = BOS; second < VOCAB_SIZE; second++) {
                for (int third = BOS; third < VOCAB_SIZE; third++) {
                    for (int fourth = BOS; fourth < VOCAB_SIZE; fourth++) {
                        int bucket = sampleBucket(first, second, third, fourth);
                        if (bucket >= 4 && bucket < 7) {
                            samples.add(sample(first, second, third, fourth));
                        }
                    }
                }
            }
        }
        int extraSamples = Math.max(64, gridSize * 8);
        for (int i = 0; i < extraSamples; i++) {
            samples.add(vectorSample(
                    new double[] {
                            lowDiscrepancy(i, 0.6180339887498948),
                            lowDiscrepancy(i, 0.4142135623730950),
                            lowDiscrepancy(i, 0.7320508075688772),
                            lowDiscrepancy(i, 0.2360679774997897)
                    },
                    RealTransformerBlockProblem::targetValue));
        }
        return List.copyOf(samples);
    }

    private static List<NeuroEvolutionSample> buildJitterSamples() {
        return List.of(
                sample(BOS, 1, 3, 5),
                sample(BOS, 2, 4, 6),
                sample(1, 3, 5, 7),
                sample(2, 4, 6, BOS),
                sample(5, 3, 1, 7),
                sample(6, 4, 2, BOS));
    }

    private static List<double[]> buildKernelCenters() {
        return List.of(
                sequence(BOS, 1, 3, 5),
                sequence(BOS, 2, 4, 6),
                sequence(1, 3, 5, 7),
                sequence(2, 4, 6, BOS),
                sequence(5, 3, 1, 7),
                sequence(6, 4, 2, BOS),
                sequence(1, 1, 3, 5),
                sequence(2, 2, 4, 6),
                sequence(7, 5, 3, 1),
                sequence(BOS, 7, 6, 5));
    }

    private static NeuroEvolutionSample sample(
            final int first,
            final int second,
            final int third,
            final int fourth) {
        return vectorSample(sequence(first, second, third, fourth), RealTransformerBlockProblem::targetValue);
    }

    private static double[] targetValue(final double[] input) {
        return teacherTargets(trace(input));
    }

    private static TeacherTrace trace(final double[] input) {
        int[] tokens = quantizedTokens(input);
        double[][] states = embeddedSequence(tokens);
        double[][] norm1 = layerNormAll(states, NORM1_GAMMA, NORM1_BETA);
        double[][][] queries = projectHeads(norm1, QUERY_PROJECTIONS, QUERY_BIASES);
        double[][][] keys = projectHeads(norm1, KEY_PROJECTIONS, KEY_BIASES);
        double[][][] values = projectHeads(norm1, VALUE_PROJECTIONS, VALUE_BIASES);
        double[][][] attentionMaps = new double[HEADS][SEQUENCE_LENGTH][SEQUENCE_LENGTH];
        double[][] attentionResidual = new double[SEQUENCE_LENGTH][MODEL_DIMENSIONS];

        for (int position = 0; position < SEQUENCE_LENGTH; position++) {
            double[] concatenatedHeads = new double[HEADS * HEAD_DIMENSIONS];
            for (int head = 0; head < HEADS; head++) {
                double[] weights = attentionWeights(queries[head][position], keys[head]);
                attentionMaps[head][position] = weights;
                double[] headOutput = weightedValue(weights, values[head]);
                System.arraycopy(headOutput, 0, concatenatedHeads, head * HEAD_DIMENSIONS, HEAD_DIMENSIONS);
            }
            double[] projectedAttention = matrixVectorWithBias(
                    ATTENTION_OUTPUT_PROJECTION,
                    concatenatedHeads,
                    ATTENTION_OUTPUT_BIAS);
            attentionResidual[position] = add(states[position], projectedAttention);
        }

        double[][] norm2 = layerNormAll(attentionResidual, NORM2_GAMMA, NORM2_BETA);
        double[][] mlpHidden = new double[SEQUENCE_LENGTH][MLP_DIMENSIONS];
        double[][] finalResidual = new double[SEQUENCE_LENGTH][MODEL_DIMENSIONS];
        for (int position = 0; position < SEQUENCE_LENGTH; position++) {
            mlpHidden[position] = gelu(matrixVectorWithBias(MLP_INPUT_PROJECTION, norm2[position], MLP_INPUT_BIAS));
            double[] mlpOutput = matrixVectorWithBias(MLP_OUTPUT_PROJECTION, mlpHidden[position], MLP_OUTPUT_BIAS);
            finalResidual[position] = add(attentionResidual[position], mlpOutput);
        }
        return new TeacherTrace(finalResidual, norm1, norm2, queries, keys, values, attentionMaps, mlpHidden);
    }

    private static double[] teacherTargets(final TeacherTrace trace) {
        double[] result = new double[OUTPUT_DIMENSIONS];
        int index = FINAL_OFFSET;
        index = appendMatrixSignals(result, index, trace.finalResidual(), 0.62);
        index = appendMatrixSignals(result, index, trace.norm1(), 0.58);
        index = appendMatrixSignals(result, index, trace.norm2(), 0.58);
        index = appendProjectedSignals(result, index, trace.queries(), 0.78);
        index = appendProjectedSignals(result, index, trace.keys(), 0.78);
        index = appendProjectedSignals(result, index, trace.values(), 0.72);
        for (double[][] head : trace.attentionMaps()) {
            for (double[] queryWeights : head) {
                for (double weight : queryWeights) {
                    result[index++] = clamp01(weight);
                }
            }
        }
        appendMatrixSignals(result, index, trace.mlpHidden(), 0.54);
        return result;
    }

    private static int appendMatrixSignals(
            final double[] result,
            final int start,
            final double[][] values,
            final double gain) {
        int index = start;
        for (double[] row : values) {
            for (double value : row) {
                result[index++] = signal(value, gain);
            }
        }
        return index;
    }

    private static int appendProjectedSignals(
            final double[] result,
            final int start,
            final double[][][] values,
            final double gain) {
        int index = start;
        for (double[][] head : values) {
            for (double[] position : head) {
                for (double value : position) {
                    result[index++] = signal(value, gain);
                }
            }
        }
        return index;
    }

    private static double[][] embeddedSequence(final int[] tokens) {
        double[][] states = new double[SEQUENCE_LENGTH][MODEL_DIMENSIONS];
        for (int position = 0; position < SEQUENCE_LENGTH; position++) {
            states[position] = add(TOKEN_EMBEDDINGS[tokens[position]], POSITION_EMBEDDINGS[position]);
        }
        return states;
    }

    private static double[][] layerNormAll(
            final double[][] states,
            final double[] gamma,
            final double[] beta) {
        double[][] result = new double[states.length][MODEL_DIMENSIONS];
        for (int position = 0; position < states.length; position++) {
            result[position] = layerNorm(states[position], gamma, beta);
        }
        return result;
    }

    private static double[] layerNorm(final double[] values, final double[] gamma, final double[] beta) {
        double mean = 0.0;
        for (double value : values) {
            mean += value;
        }
        mean /= values.length;

        double variance = 0.0;
        for (double value : values) {
            double centered = value - mean;
            variance += centered * centered;
        }
        variance /= values.length;

        double[] result = new double[values.length];
        double inverseStdDev = 1.0 / Math.sqrt(variance + LAYER_NORM_EPSILON);
        for (int dimension = 0; dimension < values.length; dimension++) {
            result[dimension] = (values[dimension] - mean) * inverseStdDev * gamma[dimension] + beta[dimension];
        }
        return result;
    }

    private static double[][][] projectHeads(
            final double[][] states,
            final double[][][] projections,
            final double[][] biases) {
        double[][][] result = new double[HEADS][SEQUENCE_LENGTH][HEAD_DIMENSIONS];
        for (int head = 0; head < HEADS; head++) {
            for (int position = 0; position < SEQUENCE_LENGTH; position++) {
                result[head][position] = matrixVectorWithBias(projections[head], states[position], biases[head]);
            }
        }
        return result;
    }

    private static double[] attentionWeights(final double[] query, final double[][] keys) {
        double[] scores = new double[SEQUENCE_LENGTH];
        double max = Double.NEGATIVE_INFINITY;
        for (int position = 0; position < SEQUENCE_LENGTH; position++) {
            scores[position] = ATTENTION_LOGIT_SCALE * dot(query, keys[position]) / Math.sqrt(HEAD_DIMENSIONS);
            max = Math.max(max, scores[position]);
        }
        double total = 0.0;
        for (int position = 0; position < SEQUENCE_LENGTH; position++) {
            scores[position] = Math.exp(scores[position] - max);
            total += scores[position];
        }
        for (int position = 0; position < SEQUENCE_LENGTH; position++) {
            scores[position] /= total;
        }
        return scores;
    }

    private static double[] weightedValue(final double[] weights, final double[][] values) {
        double[] result = new double[HEAD_DIMENSIONS];
        for (int position = 0; position < SEQUENCE_LENGTH; position++) {
            for (int dimension = 0; dimension < HEAD_DIMENSIONS; dimension++) {
                result[dimension] += weights[position] * values[position][dimension];
            }
        }
        return result;
    }

    private static double[] matrixVectorWithBias(
            final double[][] matrix,
            final double[] vector,
            final double[] bias) {
        double[] result = new double[matrix.length];
        for (int row = 0; row < matrix.length; row++) {
            result[row] = dot(matrix[row], vector) + bias[row];
        }
        return result;
    }

    private static double[] gelu(final double[] values) {
        double[] result = new double[values.length];
        for (int i = 0; i < values.length; i++) {
            double x = values[i];
            result[i] = 0.5 * x * (1.0 + Math.tanh(0.7978845608028654 * (x + 0.044715 * x * x * x)));
        }
        return result;
    }

    private static double[] add(final double[] left, final double[] right) {
        double[] result = new double[left.length];
        for (int i = 0; i < result.length; i++) {
            result[i] = left[i] + right[i];
        }
        return result;
    }

    private static double dot(final double[] left, final double[] right) {
        double total = 0.0;
        for (int i = 0; i < left.length; i++) {
            total += left[i] * right[i];
        }
        return total;
    }

    private static double[] sequence(final int... tokens) {
        if (tokens.length != SEQUENCE_LENGTH) {
            throw new IllegalArgumentException("Real transformer token sequence must contain "
                    + SEQUENCE_LENGTH + " tokens.");
        }
        double[] input = new double[SEQUENCE_LENGTH];
        for (int i = 0; i < tokens.length; i++) {
            input[i] = tokenCode(tokens[i]);
        }
        return input;
    }

    private static int[] quantizedTokens(final double[] input) {
        int[] tokens = new int[input.length];
        for (int i = 0; i < input.length; i++) {
            tokens[i] = nearestToken(clamp01(input[i]));
        }
        return tokens;
    }

    private static double tokenCode(final int token) {
        if (token < BOS || token >= VOCAB_SIZE) {
            throw new IllegalArgumentException("Token must be in the real transformer block vocabulary range.");
        }
        return TOKEN_CODES[token];
    }

    private static int nearestToken(final double value) {
        int nearest = BOS;
        double bestDistance = Double.POSITIVE_INFINITY;
        for (int token = BOS; token < TOKEN_CODES.length; token++) {
            double distance = Math.abs(value - TOKEN_CODES[token]);
            if (distance < bestDistance) {
                bestDistance = distance;
                nearest = token;
            }
        }
        return nearest;
    }

    private static String residualLabel(final String prefix, final int index) {
        return prefix + ".P" + (index / MODEL_DIMENSIONS) + ".D" + (index % MODEL_DIMENSIONS);
    }

    private static String qkvOutputLabel(final int outputIndex) {
        int kind;
        int kindOffset;
        if (outputIndex < KEY_OFFSET) {
            kind = 0;
            kindOffset = QUERY_OFFSET;
        } else if (outputIndex < VALUE_OFFSET) {
            kind = 1;
            kindOffset = KEY_OFFSET;
        } else {
            kind = 2;
            kindOffset = VALUE_OFFSET;
        }
        int index = outputIndex - kindOffset;
        int valuesPerHead = SEQUENCE_LENGTH * HEAD_DIMENSIONS;
        int head = index / valuesPerHead;
        int headIndex = index % valuesPerHead;
        return qkvLabel(kind) + head + ".P" + (headIndex / HEAD_DIMENSIONS) + ".D" + (headIndex % HEAD_DIMENSIONS);
    }

    private static String qkvLabel(final int kind) {
        return switch (kind) {
            case 0 -> "Q";
            case 1 -> "K";
            case 2 -> "V";
            default -> throw new IllegalArgumentException("Unknown transformer projection kind.");
        };
    }

    private static int sampleBucket(
            final int first,
            final int second,
            final int third,
            final int fourth) {
        int hash = 17;
        hash = 31 * hash + first * 11;
        hash = 31 * hash + second * 17;
        hash = 31 * hash + third * 23;
        hash = 31 * hash + fourth * 29;
        return Math.floorMod(hash, 97);
    }

    private static double signal(final double value, final double gain) {
        return clamp01(0.5 + 0.45 * Math.tanh(gain * value));
    }

    private static double[][] matrix(
            final int rows,
            final int columns,
            final double salt,
            final double scale) {
        double[][] result = new double[rows][columns];
        double normalizer = Math.sqrt(columns);
        for (int row = 0; row < rows; row++) {
            for (int column = 0; column < columns; column++) {
                result[row][column] = scale * pattern(row, column, salt) / normalizer;
            }
        }
        return result;
    }

    private static double[][][] tensor(
            final int heads,
            final int rows,
            final int columns,
            final double salt,
            final double scale) {
        double[][][] result = new double[heads][rows][columns];
        for (int head = 0; head < heads; head++) {
            result[head] = matrix(rows, columns, salt + head * 0.37, scale);
        }
        return result;
    }

    private static double[] vector(
            final int length,
            final double salt,
            final double center,
            final double scale) {
        double[] result = new double[length];
        for (int i = 0; i < length; i++) {
            result[i] = center + scale * pattern(i, 0, salt);
        }
        return result;
    }

    private static double[][] headBiases(final double salt, final double scale) {
        double[][] result = new double[HEADS][HEAD_DIMENSIONS];
        for (int head = 0; head < HEADS; head++) {
            result[head] = vector(HEAD_DIMENSIONS, salt + head * 0.29, 0.0, scale);
        }
        return result;
    }

    private static double pattern(final int row, final int column, final double salt) {
        double r = row + 1.0;
        double c = column + 1.0;
        return 0.72 * Math.sin((r + 0.31) * (c + 0.73) * salt)
                + 0.48 * Math.cos((r + 1.17) * (c + 0.19) * (salt + 0.41))
                + 0.25 * Math.sin((r + c + 0.53) * (salt + 1.03));
    }

    private static double lowDiscrepancy(final int index, final double step) {
        double value = 0.5 + (index + 1) * step;
        return value - Math.floor(value);
    }

    private record TeacherTrace(
            double[][] finalResidual,
            double[][] norm1,
            double[][] norm2,
            double[][][] queries,
            double[][][] keys,
            double[][][] values,
            double[][][] attentionMaps,
            double[][] mlpHidden) {
    }
}
