package com.github.javachaos.javaneuralnetwork.examples;

import java.util.ArrayList;
import java.util.List;

/**
 * Teacher-student benchmark generated by a tiny transformer-style block.
 */
public final class TransformerBlockProblem extends NeuroEvolutionProblem {

    private static final String KEY = "transformer-block";
    private static final int SEQUENCE_LENGTH = 3;
    private static final int VOCAB_SIZE = 5;
    private static final int MODEL_DIMENSIONS = 3;
    private static final int HEADS = 2;
    private static final int HEAD_DIMENSIONS = 2;
    private static final int FINAL_OUTPUTS = SEQUENCE_LENGTH * MODEL_DIMENSIONS;
    private static final int QKV_OUTPUTS_PER_KIND = HEADS * SEQUENCE_LENGTH * HEAD_DIMENSIONS;
    private static final int ATTENTION_OUTPUTS_PER_HEAD = SEQUENCE_LENGTH * SEQUENCE_LENGTH;
    private static final int QKV_OUTPUTS = HEADS * 3 * SEQUENCE_LENGTH * HEAD_DIMENSIONS;
    private static final int ATTENTION_OUTPUTS = HEADS * SEQUENCE_LENGTH * SEQUENCE_LENGTH;
    private static final int OUTPUT_DIMENSIONS = FINAL_OUTPUTS + QKV_OUTPUTS + ATTENTION_OUTPUTS;
    private static final double ATTENTION_OBJECTIVE_WEIGHT = 2.5;
    private static final NeuroEvolutionFreeEnergyProfile FREE_ENERGY_PROFILE =
            NeuroEvolutionFreeEnergyProfile.predictiveCoding(0.025, 1.0, 0.25, 0.006, 3.0);
    private static final double ATTENTION_LOGIT_SCALE = 3.8;
    private static final int BOS = 0;
    private static final int RED = 1;
    private static final int BLUE = 2;
    private static final int CUBE = 3;
    private static final int SPHERE = 4;

    private static final String DESCRIPTION = "Transformer block is a teacher-student benchmark generated by a "
            + "fixed tiny transformer-style layer. The three raw inputs are scrambled token codes. The target exposes "
            + "the teacher block's final transformed sequence plus its hidden Q/K/V projections and two-head attention "
            + "weight maps. Internally the teacher uses token embeddings, positional embeddings, two learned Q/K/V "
            + "attention heads, an output projection, an attention residual path, a small feed-forward projection, and "
            + "a second residual path. The evolved learner does not contain named transformer components, but good "
            + "champions must rediscover their behavior well enough to match both the final outputs and the internal "
            + "attention machinery on held-out token sequences.";
    private static final String[] TOKEN_LABELS = {
            "BOS", "RED", "BLUE", "CUBE", "SPHERE"
    };
    private static final double[] TOKEN_CODES = {
            0.00, 0.76, 0.25, 1.00, 0.50
    };
    private static final double[][] TOKEN_EMBEDDINGS = {
            {-0.30, 0.10, 0.45},
            {0.72, -0.38, 0.18},
            {-0.58, 0.64, -0.22},
            {0.14, 0.76, 0.52},
            {-0.66, -0.18, 0.70}
    };
    private static final double[][] POSITION_EMBEDDINGS = {
            {-0.16, 0.08, 0.20},
            {0.12, -0.22, 0.04},
            {0.20, 0.14, -0.18}
    };
    private static final double[][][] QUERY_PROJECTIONS = {
            {
                    {0.80, -0.35, 0.22},
                    {-0.18, 0.72, 0.41}
            },
            {
                    {-0.54, 0.28, 0.69},
                    {0.64, 0.19, -0.31}
            }
    };
    private static final double[][][] KEY_PROJECTIONS = {
            {
                    {0.56, -0.48, 0.36},
                    {0.26, 0.68, -0.21}
            },
            {
                    {-0.38, 0.74, 0.17},
                    {0.71, -0.15, 0.44}
            }
    };
    private static final double[][][] VALUE_PROJECTIONS = {
            {
                    {0.61, 0.16, -0.42},
                    {-0.24, 0.53, 0.58}
            },
            {
                    {0.18, -0.62, 0.70},
                    {0.66, 0.34, -0.12}
            }
    };
    private static final double[][] OUTPUT_PROJECTION = {
            {0.46, -0.31, 0.28, 0.53},
            {-0.42, 0.59, 0.37, -0.24},
            {0.34, 0.25, -0.56, 0.48}
    };
    private static final double[][] FEED_FORWARD_IN = {
            {0.72, -0.30, 0.18},
            {-0.44, 0.68, 0.26},
            {0.21, 0.38, -0.62},
            {-0.18, 0.51, 0.57}
    };
    private static final double[][] FEED_FORWARD_OUT = {
            {0.35, -0.28, 0.46, 0.21},
            {-0.31, 0.54, 0.18, -0.37},
            {0.42, 0.16, -0.24, 0.49}
    };

    public TransformerBlockProblem(final int gridSize) {
        super(
                KEY,
                "Transformer block",
                DESCRIPTION,
                List.of("transformer-layer", "qkv", "multi-head", "token-embedding", "residual-transformer"),
                SEQUENCE_LENGTH,
                OUTPUT_DIMENSIONS,
                buildTrainingSamples(),
                buildGeneralizationSamples(Math.max(gridSize, DEFAULT_GRID_SIZE)),
                buildJitterSamples(),
                buildKernelCenters(),
                false,
                TransformerBlockProblem::targetValue);
    }

    public double[] encodeTokenSequence(final int... tokens) {
        return sequence(tokens);
    }

    @Override
    public String outputLabel(final int outputIndex) {
        if (outputIndex < 0 || outputIndex >= OUTPUT_DIMENSIONS) {
            throw new IllegalArgumentException("Output index must be in the transformer block output range.");
        }
        if (outputIndex < FINAL_OUTPUTS) {
            return "Y" + (outputIndex / MODEL_DIMENSIONS) + "." + (outputIndex % MODEL_DIMENSIONS);
        }
        int index = outputIndex - FINAL_OUTPUTS;
        if (index < QKV_OUTPUTS) {
            int valuesPerHead = SEQUENCE_LENGTH * HEAD_DIMENSIONS;
            int valuesPerKind = HEADS * valuesPerHead;
            int kind = index / valuesPerKind;
            int kindIndex = index % valuesPerKind;
            int head = kindIndex / valuesPerHead;
            int headIndex = kindIndex % valuesPerHead;
            return qkvLabel(kind) + head + ".P" + (headIndex / HEAD_DIMENSIONS) + ".D" + (headIndex % HEAD_DIMENSIONS);
        }
        index -= QKV_OUTPUTS;
        int valuesPerAttentionHead = SEQUENCE_LENGTH * SEQUENCE_LENGTH;
        int head = index / valuesPerAttentionHead;
        int headIndex = index % valuesPerAttentionHead;
        return "A" + head + ".Q" + (headIndex / SEQUENCE_LENGTH) + ".K" + (headIndex % SEQUENCE_LENGTH);
    }

    @Override
    public List<NeuroEvolutionOutputGroup> outputGroups() {
        return List.of(
                new NeuroEvolutionOutputGroup("Final residual outputs", 0, FINAL_OUTPUTS),
                new NeuroEvolutionOutputGroup(
                        "Query projections",
                        FINAL_OUTPUTS,
                        FINAL_OUTPUTS + QKV_OUTPUTS_PER_KIND),
                new NeuroEvolutionOutputGroup(
                        "Key projections",
                        FINAL_OUTPUTS + QKV_OUTPUTS_PER_KIND,
                        FINAL_OUTPUTS + 2 * QKV_OUTPUTS_PER_KIND),
                new NeuroEvolutionOutputGroup(
                        "Value projections",
                        FINAL_OUTPUTS + 2 * QKV_OUTPUTS_PER_KIND,
                        FINAL_OUTPUTS + QKV_OUTPUTS),
                new NeuroEvolutionOutputGroup(
                        "Attention head 0",
                        FINAL_OUTPUTS + QKV_OUTPUTS,
                        FINAL_OUTPUTS + QKV_OUTPUTS + ATTENTION_OUTPUTS_PER_HEAD,
                        ATTENTION_OBJECTIVE_WEIGHT),
                new NeuroEvolutionOutputGroup(
                        "Attention head 1",
                        FINAL_OUTPUTS + QKV_OUTPUTS + ATTENTION_OUTPUTS_PER_HEAD,
                        OUTPUT_DIMENSIONS,
                        ATTENTION_OBJECTIVE_WEIGHT));
    }

    @Override
    public NeuroEvolutionFreeEnergyProfile freeEnergyProfile() {
        return FREE_ENERGY_PROFILE;
    }

    public String tokenLabel(final int token) {
        if (token < BOS || token >= VOCAB_SIZE) {
            throw new IllegalArgumentException("Token must be in the transformer block vocabulary range.");
        }
        return TOKEN_LABELS[token];
    }

    private static List<NeuroEvolutionSample> buildTrainingSamples() {
        List<NeuroEvolutionSample> samples = new ArrayList<>();
        for (int first = BOS; first < VOCAB_SIZE; first++) {
            for (int second = BOS; second < VOCAB_SIZE; second++) {
                for (int third = BOS; third < VOCAB_SIZE; third++) {
                    if (!isHeldOut(first, second, third)) {
                        samples.add(sample(first, second, third));
                    }
                }
            }
        }
        return List.copyOf(samples);
    }

    private static List<NeuroEvolutionSample> buildGeneralizationSamples(final int gridSize) {
        List<NeuroEvolutionSample> samples = new ArrayList<>();
        for (int first = BOS; first < VOCAB_SIZE; first++) {
            for (int second = BOS; second < VOCAB_SIZE; second++) {
                for (int third = BOS; third < VOCAB_SIZE; third++) {
                    if (isHeldOut(first, second, third)) {
                        samples.add(sample(first, second, third));
                    }
                }
            }
        }
        int extraSamples = Math.max(36, gridSize * 3);
        for (int i = 0; i < extraSamples; i++) {
            samples.add(vectorSample(
                    new double[] {
                            lowDiscrepancy(i, 0.6180339887498948),
                            lowDiscrepancy(i, 0.4142135623730950),
                            lowDiscrepancy(i, 0.7320508075688772)
                    },
                    TransformerBlockProblem::targetValue));
        }
        return List.copyOf(samples);
    }

    private static List<NeuroEvolutionSample> buildJitterSamples() {
        return List.of(
                sample(BOS, RED, CUBE),
                sample(BOS, BLUE, SPHERE),
                sample(RED, CUBE, RED),
                sample(BLUE, SPHERE, CUBE),
                sample(SPHERE, RED, BLUE));
    }

    private static List<double[]> buildKernelCenters() {
        return List.of(
                sequence(BOS, RED, CUBE),
                sequence(BOS, BLUE, SPHERE),
                sequence(RED, CUBE, SPHERE),
                sequence(BLUE, SPHERE, RED),
                sequence(CUBE, RED, BLUE),
                sequence(SPHERE, BLUE, CUBE),
                sequence(RED, RED, CUBE),
                sequence(BLUE, CUBE, SPHERE));
    }

    private static NeuroEvolutionSample sample(final int first, final int second, final int third) {
        return vectorSample(sequence(first, second, third), TransformerBlockProblem::targetValue);
    }

    private static double[] targetValue(final double[] input) {
        int[] tokens = quantizedTokens(input);
        double[][] states = embeddedSequence(tokens);
        double[][][] queries = projectAll(states, QUERY_PROJECTIONS);
        double[][][] keys = projectAll(states, KEY_PROJECTIONS);
        double[][][] values = projectAll(states, VALUE_PROJECTIONS);
        double[][] outputs = new double[SEQUENCE_LENGTH][MODEL_DIMENSIONS];
        double[][][] attentionMaps = new double[HEADS][SEQUENCE_LENGTH][SEQUENCE_LENGTH];

        for (int position = 0; position < SEQUENCE_LENGTH; position++) {
            double[] concatenatedHeads = new double[HEADS * HEAD_DIMENSIONS];
            for (int head = 0; head < HEADS; head++) {
                double[] weights = attentionWeights(queries[head][position], keys[head]);
                attentionMaps[head][position] = weights;
                double[] headOutput = weightedValue(weights, values[head]);
                System.arraycopy(headOutput, 0, concatenatedHeads, head * HEAD_DIMENSIONS, HEAD_DIMENSIONS);
            }
            double[] attentionProjected = matrixVector(OUTPUT_PROJECTION, concatenatedHeads);
            double[] attentionResidual = add(states[position], attentionProjected);
            double[] feedForward = matrixVector(FEED_FORWARD_OUT, relu(matrixVector(FEED_FORWARD_IN, attentionResidual)));
            outputs[position] = squash(add(attentionResidual, scale(feedForward, 0.35)));
        }
        return teacherTargets(outputs, queries, keys, values, attentionMaps);
    }

    private static double[][] embeddedSequence(final int[] tokens) {
        double[][] states = new double[SEQUENCE_LENGTH][MODEL_DIMENSIONS];
        for (int position = 0; position < SEQUENCE_LENGTH; position++) {
            states[position] = add(TOKEN_EMBEDDINGS[tokens[position]], POSITION_EMBEDDINGS[position]);
        }
        return states;
    }

    private static double[][][] projectAll(final double[][] states, final double[][][] projections) {
        double[][][] projected = new double[HEADS][SEQUENCE_LENGTH][HEAD_DIMENSIONS];
        for (int head = 0; head < HEADS; head++) {
            for (int position = 0; position < SEQUENCE_LENGTH; position++) {
                projected[head][position] = matrixVector(projections[head], states[position]);
            }
        }
        return projected;
    }

    private static double[] attentionWeights(final double[] query, final double[][] keys) {
        double[] scores = new double[SEQUENCE_LENGTH];
        double max = Double.NEGATIVE_INFINITY;
        for (int position = 0; position < SEQUENCE_LENGTH; position++) {
            scores[position] = ATTENTION_LOGIT_SCALE * dot(query, keys[position]) / Math.sqrt(HEAD_DIMENSIONS);
            max = Math.max(max, scores[position]);
        }
        double total = 0.0;
        for (int position = 0; position < SEQUENCE_LENGTH; position++) {
            scores[position] = Math.exp(scores[position] - max);
            total += scores[position];
        }
        for (int position = 0; position < SEQUENCE_LENGTH; position++) {
            scores[position] /= total;
        }
        return scores;
    }

    private static double[] weightedValue(final double[] weights, final double[][] values) {
        double[] result = new double[HEAD_DIMENSIONS];
        for (int position = 0; position < SEQUENCE_LENGTH; position++) {
            for (int dimension = 0; dimension < HEAD_DIMENSIONS; dimension++) {
                result[dimension] += weights[position] * values[position][dimension];
            }
        }
        return result;
    }

    private static double[] matrixVector(final double[][] matrix, final double[] vector) {
        double[] result = new double[matrix.length];
        for (int row = 0; row < matrix.length; row++) {
            result[row] = dot(matrix[row], vector);
        }
        return result;
    }

    private static double[] relu(final double[] values) {
        double[] result = new double[values.length];
        for (int i = 0; i < values.length; i++) {
            result[i] = Math.max(0.0, values[i]);
        }
        return result;
    }

    private static double[] add(final double[] left, final double[] right) {
        double[] result = new double[left.length];
        for (int i = 0; i < result.length; i++) {
            result[i] = left[i] + right[i];
        }
        return result;
    }

    private static double[] scale(final double[] values, final double scale) {
        double[] result = new double[values.length];
        for (int i = 0; i < result.length; i++) {
            result[i] = values[i] * scale;
        }
        return result;
    }

    private static double[] squash(final double[] values) {
        double[] result = new double[values.length];
        for (int i = 0; i < values.length; i++) {
            result[i] = 0.5 + 0.45 * Math.tanh(1.15 * values[i]);
        }
        return result;
    }

    private static double[] teacherTargets(
            final double[][] finalOutputs,
            final double[][][] queries,
            final double[][][] keys,
            final double[][][] values,
            final double[][][] attentionMaps) {
        double[] result = new double[OUTPUT_DIMENSIONS];
        int index = 0;
        for (double[] row : finalOutputs) {
            for (double value : row) {
                result[index++] = clamp01(value);
            }
        }
        index = appendProjected(result, index, queries);
        index = appendProjected(result, index, keys);
        index = appendProjected(result, index, values);
        for (double[][] head : attentionMaps) {
            for (double[] queryWeights : head) {
                for (double weight : queryWeights) {
                    result[index++] = clamp01(weight);
                }
            }
        }
        return result;
    }

    private static int appendProjected(
            final double[] result,
            final int start,
            final double[][][] projected) {
        int index = start;
        for (double[][] head : projected) {
            for (double[] position : head) {
                for (double value : position) {
                    result[index++] = projectedSignal(value);
                }
            }
        }
        return index;
    }

    private static double projectedSignal(final double value) {
        return 0.5 + 0.45 * Math.tanh(1.4 * value);
    }

    private static double dot(final double[] left, final double[] right) {
        double total = 0.0;
        for (int i = 0; i < left.length; i++) {
            total += left[i] * right[i];
        }
        return total;
    }

    private static double[] sequence(final int... tokens) {
        if (tokens.length != SEQUENCE_LENGTH) {
            throw new IllegalArgumentException("Transformer token sequence must contain " + SEQUENCE_LENGTH + " tokens.");
        }
        double[] input = new double[SEQUENCE_LENGTH];
        for (int i = 0; i < tokens.length; i++) {
            input[i] = tokenCode(tokens[i]);
        }
        return input;
    }

    private static int[] quantizedTokens(final double[] input) {
        int[] tokens = new int[input.length];
        for (int i = 0; i < input.length; i++) {
            tokens[i] = nearestToken(clamp01(input[i]));
        }
        return tokens;
    }

    private static double tokenCode(final int token) {
        if (token < BOS || token >= VOCAB_SIZE) {
            throw new IllegalArgumentException("Token must be in the transformer block vocabulary range.");
        }
        return TOKEN_CODES[token];
    }

    private static int nearestToken(final double value) {
        int nearest = BOS;
        double bestDistance = Double.POSITIVE_INFINITY;
        for (int token = BOS; token < TOKEN_CODES.length; token++) {
            double distance = Math.abs(value - TOKEN_CODES[token]);
            if (distance < bestDistance) {
                bestDistance = distance;
                nearest = token;
            }
        }
        return nearest;
    }

    private static boolean isHeldOut(final int first, final int second, final int third) {
        return Math.floorMod(first * 31 + second * 17 + third * 13, 7) == 0;
    }

    private static String qkvLabel(final int kind) {
        return switch (kind) {
            case 0 -> "Q";
            case 1 -> "K";
            case 2 -> "V";
            default -> throw new IllegalArgumentException("Unknown transformer projection kind.");
        };
    }

    private static double lowDiscrepancy(final int index, final double step) {
        double value = 0.5 + (index + 1) * step;
        return value - Math.floor(value);
    }
}
