package com.github.javachaos.javaneuralnetwork.examples;

/**
 * Mutations that change the learner itself instead of only changing weights.
 */
public enum XorMutationType {
    ADD_NEURON,
    REMOVE_NEURON,
    ADD_HIDDEN_LAYER,
    REMOVE_HIDDEN_LAYER,
    ADD_CONNECTION,
    REMOVE_CONNECTION,
    ADD_RECURRENT_CONNECTION,
    REMOVE_RECURRENT_CONNECTION,
    CHANGE_ACTIVATION,
    ADD_MEMORY_CELL,
    REMOVE_MEMORY_CELL,
    ADD_HEBBIAN_UPDATE,
    ADD_GRADIENT_UPDATE,
    ADD_NORMALIZATION,
    ADD_KERNEL_MEMORY,
    ADD_PHASE_ENCODING,
    ADD_SECOND_DERIVATIVE_ESTIMATE,
    CHANGE_LEARNING_SCHEDULE,
    CHANGE_LOSS_FUNCTION,
    CHANGE_INPUT_REPRESENTATION,
    PERTURB_NUMERIC_PARAMETER
}
